### ISSUE TITLE
CM-13.0 Progress

### ISSUE THREAD

**Issue by GMCadiom** [MTK-Devices-Project/android_device_htc_816g#1]
**Main porting**
- [x] Booting
- [x] WiFi
- [x] Dual SIM
- [x] SELinux
- [x] RIL
    - [ ] RIL > Signal Drop When Answering A Call When HeadSet Connected
- [x] Sensors
- [x] Camera
- [ ] ADB
- [x] MTP
    - [ ] Mass Storage > Name Wrong
- [ ] Camera
    - [x] Cupture
    - [ ] Vedio Recording
- [x] HeadSet Icon
- [x] Sensors
    - [x] Lights
    - [x] Rotation 
- [x] GPS
- [ ] OTG
- [x] Data Connection
- [x] Screen Record
- [x] Off-Line Charging
- [x] HD Games
- [x] Tethering
- [x] FMRadio
- [x] KEYS & Buttons
- [ ] VPN
- [ ] 2g/3g Switcher

**Comment by GMCadiom** [comment]
@Firelord1
can u please take a look here and see if u can help me make ADB and Mass Storage works ??

**Comment by GMCadiom** [comment]
v3 Change log :
- [x] FMRadio
- [x] Data Connection
- [x] KEYS & Buttons

**Comment by FireLord1** [comment]
i think we have MTP now bro..

**Comment by GMCadiom** [comment]
@FireLord1 
Yup
mtp now

**Comment by GMCadiom** [comment]
v4 Change log :
BootLoop on logo and can't detected on ADB to see where the error from

**Comment by GMCadiom** [comment]
v4 Rom Booted After replace from v3 :
bin/surfaceflinger
lib/libEGL.so
lib/libgui.so
lib/libsurfaceflinger.so
lib/libutils.so

**Comment by GMCadiom** [comment]
v5 Change log :
- [x] HeadSet Icon
- [x] GPS
- [x] Screen Record
- [x] HD Games

**Comment by GMCadiom** [comment]
device SOLD xD :D
